import { Cart } from "@/components";
import { DefaultLayout } from "@/layouts";
import { getProfileProps } from "@/lib";
import { UserModel } from "@/models";
import { UserJson } from "@/types/json";
import Head from "next/head";
import { GetServerSidePropsContext } from "next/types";

type Props = {
  profile: UserJson | null;
};

const Page = ({ profile }: Props) => {
  return (
    <DefaultLayout profile={new UserModel(profile)}>
      <Head>
        <title>Giỏ hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cart />
    </DefaultLayout>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { props } = await getProfileProps(context);
  return { props };
};

export default Page;
