import Head from "next/head";
import { AdminLayout } from "@/layouts";
import { BlogForm, DashboardPaper } from "@/components";

type Props = {};

const CreateBlog = (props: Props) => {
  return (
    <AdminLayout pageTitle="Thêm mới bài viết">
      <>
        <Head>
          <title>Thêm mới bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin thêm mới bài viết">
          <BlogForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export default CreateBlog;
