import Head from "next/head";
import { AdminLayout } from "@/layouts";
import { BlogForm, DashboardPaper } from "@/components";
import { UserJson } from "@/types/json";
import { UserModel } from "@/models";
import { requireAdminProps } from "@/lib";
import { GetServerSidePropsContext } from "next";
type Props = { profile: UserJson | null };

const CreateBlog = ({ profile }: Props) => {
  return (
    <AdminLayout pageTitle="Thêm mới bài viết" profile={new UserModel(profile)}>
      <>
        <Head>
          <title>Thêm mới bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin thêm mới bài viết">
          <BlogForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return requireAdminProps(context);
};

export default CreateBlog;
