import Head from "next/head";
import { useEffect } from "react";

import { DashboardPaper, ProductForm } from "@/components";
import { AdminLayout } from "@/layouts";
import { requireAdminProps } from "@/lib";
import { UserModel } from "@/models";
import { groupProductActions } from "@/redux/slice/groupProductSlice";
import { useAppDispatch } from "@/redux/store";
import { UserJson } from "@/types/json";
import { GetServerSidePropsContext } from "next";

type Props = { profile: UserJson | null };

const AddProduct = ({ profile }: Props) => {
  const appDispatch = useAppDispatch();

  useEffect(() => {
    appDispatch(
      groupProductActions.fetchGetAll({
        sortType: "ASC",
        sortBy: "id",
      })
    );
  }, []);

  return (
    <AdminLayout pageTitle="Sản phẩm" profile={new UserModel(profile)}>
      <>
        <Head>
          <title>Thêm mới sản phẩm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin thêm mới sản phẩm">
          <ProductForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return requireAdminProps(context);
};

export default AddProduct;
