import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { useSelector } from "react-redux";
import { DashboardPaper, ProductForm } from "../../../components";
import { AdminLayout } from "../../../layouts";
import { fetchSelector } from "../../../redux/slice/fetchSlice";
import { groupProductActions } from "../../../redux/slice/groupProductSlice";
import { useAppDispatch } from "../../../redux/store";

type Props = {};

const AddProduct = (props: Props) => {
  const router = useRouter();
  const appDispatch = useAppDispatch();
  const { isBack } = useSelector(fetchSelector);

  useEffect(() => {
    appDispatch(
      groupProductActions.fetchGetAll({
        sortType: "asc",
        sortBy: "id",
      })
    );
  }, []);

  return (
    <AdminLayout pageTitle="Sản phẩm">
      <>
        <Head>
          <title>Thêm mới sản phẩm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin thêm mới sản phẩm">
          <ProductForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export default AddProduct;
