import Head from "next/head";
import { AdminLayout } from "@/layouts";
import { AdvertisementForm, DashboardPaper } from "@/components";
import { UserJson } from "@/types/json";
import { UserModel } from "@/models";
import { requireAdminProps } from "@/lib";
import { GetServerSidePropsContext } from "next";

type Props = { profile: UserJson | null };

const Page = ({ profile }: Props) => {
  return (
    <AdminLayout
      pageTitle="Chỉnh sửa quảng cáo"
      profile={new UserModel(profile)}
    >
      <>
        <Head>
          <title>Chỉnh sửa quảng cáo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin quảng cáo">
          <AdvertisementForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return requireAdminProps(context);
};

export default Page;
