import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { BlogContent, DashboardPaper } from "../../../../components";
import { AdminLayout } from "../../../../layouts";
import { blogActions, blogSelector } from "../../../../redux/slice/blogSlice";
import { useAppDispatch } from "../../../../redux/store";

type Props = {};

const Page = (props: Props) => {
  const router = useRouter();
  const appDispatch = useAppDispatch();
  const { current, blogEditing } = useSelector(blogSelector);

  useEffect(() => {
    const { id } = router.query;
    appDispatch(blogActions.fetchGetBlogById(+`${id}`));
  }, [router.query]);

  const blog = current || blogEditing;

  return (
    <AdminLayout pageTitle="Chỉnh sửa bài viết">
      <>
        <Head>
          <title>Chỉnh sửa bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <DashboardPaper title="Xem trước bài viết">
          {!blog ? (
            <div>Không tìm thấy bài viết</div>
          ) : (
            <BlogContent blog={blog} />
          )}
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export default Page;
