import { BlogForm, DashboardPaper } from "@/components";
import { AdminLayout } from "@/layouts";
import { blogActions } from "@/redux/slice/blogSlice";
import { useAppDispatch } from "@/redux/store";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

type Props = {};

const Page = (props: Props) => {
  const router = useRouter();
  const appDispatch = useAppDispatch();

  useEffect(() => {
    const { id } = router.query;
    appDispatch(blogActions.fetchGetById(+`${id}`));
  }, [router.query]);

  return (
    <AdminLayout pageTitle="Chỉnh sửa bài viết">
      <>
        <Head>
          <title>Chỉnh sửa bài viết</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin bài viết">
          <BlogForm />
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export default Page;
