import { GroupProductApi, ProductApi } from "@/api";
import { FilterProducts } from "@/components";
import { DefaultLayout } from "@/layouts";
import { getProfileProps } from "@/lib";
import {
  GroupProductModel,
  ProductModel,
  ResponseGetAllModel,
  UserModel,
} from "@/models";
import { GroupProductJson, ProductJson, UserJson } from "@/types/json";
import { publicRoutes } from "@/utils/routes";
import { GetServerSidePropsContext } from "next";

import Head from "next/head";

type Props = {
  productData: { items: ProductJson[]; count: number };
  groupProductData: { items: GroupProductJson[]; count: number };
  profile: UserJson | null;
};

const LIMIT = 24;
const pApi = new ProductApi();
const gpApi = new GroupProductApi();
const Page = ({
  productData: data1,
  groupProductData: data2,
  profile,
}: Props) => {
  const productData: ResponseGetAllModel<ProductModel> =
    new ResponseGetAllModel(pApi.getListFromJson(data1.items), data1.count);
  const groupProductData: ResponseGetAllModel<GroupProductModel> =
    new ResponseGetAllModel(gpApi.getListFromJson(data2.items), data2.count);

  return (
    <DefaultLayout profile={new UserModel(profile)}>
      <Head>
        <title>Tất cả sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterProducts
        totalProducts={productData.count}
        breadcrumbs={{
          links: [
            {
              href: publicRoutes.home,
              label: "Trang chủ",
            },
          ],
          current: "Tất cả sản phẩm",
        }}
        groupProductData={groupProductData}
        pathName="/product"
        productData={productData}
        totalPages={productData.getTotalPages(LIMIT)}
      />
    </DefaultLayout>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const {
      group_product_slug,
      p,
      sortBy,
      sortType,
      v_ids,
      min_price,
      max_price,
    } = context.query;
    const [productData, groupProductData] = await Promise.all([
      pApi.getAllJson({
        limit: LIMIT,
        product_variants: true,
        ...(p ? { p: +`${p}` } : {}),
        ...(sortBy ? { sortBy: `${sortBy}` } : {}),
        ...(group_product_slug
          ? { group_product_slug: `${group_product_slug}` }
          : {}),
        ...(sortType
          ? { sortType: `${sortType}` === "DESC" ? "DESC" : "ASC" }
          : {}),
        ...(v_ids ? { v_ids: `${v_ids}` } : {}),
        ...(min_price ? { min_price: +`${min_price}` } : {}),
        ...(max_price ? { max_price: +`${max_price}` } : {}),
      }),
      gpApi.getAllJson({
        sortBy: "slug",
        sortType: "ASC",
      }),
    ]);

    const { props } = await getProfileProps(context);
    return {
      props: { ...props, productData, groupProductData },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

export default Page;
