import { Grid } from "@mui/material";
import Head from "next/head";
import { ChangeEvent, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { AdminLayout } from "../../../layouts";

import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { DashboardPaper, FooterForm, InputControl } from "../../../components";
import { advertisementActions } from "../../../redux/slice/advertisementSlice";
import { useAppDispatch } from "../../../redux/store";
import { fetchSelector } from "../../../redux/slice/fetchSlice";
import { CreateAdvertisementDTO } from "../../../types/dtos";

type Props = {};

const CreateAdvertisement = (props: Props) => {
  const router = useRouter();
  const appDispatch = useAppDispatch();
  const { isLoading } = useSelector(fetchSelector);
  const [files, setFiles] = useState<FileList | null>(null);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateAdvertisementDTO>({
    defaultValues: {
      href: "/",
      title: "",
      page: "Trang chủ",
    },
  });

  const onSubmit: SubmitHandler<CreateAdvertisementDTO> = (data) => {
    appDispatch(
      advertisementActions.fetchCreate({
        files,
        dto: data,
      })
    );
  };

  return (
    <AdminLayout pageTitle="Thêm mới quảng cáo">
      <>
        <Head>
          <title>Thêm mới quảng cáo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DashboardPaper title="Thông tin thêm mới quảng cáo">
          <form onSubmit={handleSubmit(onSubmit)}>
            <Grid container rowSpacing={3} columnSpacing={3}>
              <Grid item xs={12}>
                <InputControl
                  register={register("title", {
                    required: {
                      value: true,
                      message: "Tiêu đề không được để trống",
                    },
                  })}
                  error={errors.title}
                  label="Tiêu đề"
                  required={true}
                />
              </Grid>
              <Grid item xs={12}>
                <InputControl register={register("page")} label="Trang" />
              </Grid>
              <Grid item xs={12}>
                <InputControl register={register("href")} label="Liên kết" />
              </Grid>
              <Grid item xs={12}>
                <InputControl
                  label="Hình ảnh"
                  type="file"
                  onChange={(e: ChangeEvent<HTMLInputElement>) =>
                    setFiles(e.target.files)
                  }
                />
              </Grid>
              <Grid item xs={12}>
                <FooterForm isLoading={isLoading} />
              </Grid>
            </Grid>
          </form>
        </DashboardPaper>
      </>
    </AdminLayout>
  );
};

export default CreateAdvertisement;
