import Head from "next/head";
import React from "react";
import { useAuthContext } from "../../context/AuthContext";
import { AccountLayout } from "../../layouts";
import { useForm, SubmitHandler } from "react-hook-form";
import {
  ChangeProfile,
  changeProfile as apiChangeProfile,
} from "../../apis/auth";
import styles from "../../styles/Profile.module.css";
import { MSG_SUCCESS } from "../../utils/constants";
import { useSnackbarContext } from "../../context/SnackbarContext";
import { InputControl } from "../../components";

type Props = {};

const Profile = (props: Props) => {
  const { profile, changeProfile } = useAuthContext();
  const { show } = useSnackbarContext();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<ChangeProfile>();
  const onSubmit: SubmitHandler<ChangeProfile> = async (data) => {
    try {
      const res = await apiChangeProfile(data);
      console.log(data, res);
      const { message, data: _data } = res;
      if (message === MSG_SUCCESS) {
        changeProfile(_data);
        show("Cập nhật thành công", "success");
      }
    } catch (error) {
      console.log(error);
    }
  };
  return profile ? (
    <AccountLayout titleHeading="Thông tin tài khoản">
      <>
        <Head>
          <title>Thông tin tài khoản</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
          <InputControl
            defaultValue={profile.email}
            required={true}
            register={register("email", {
              required: {
                value: true,
                message: "Email không được bỏ trống",
              },
              pattern: {
                value: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
                message: "Địa chỉ email không hợp lệ",
              },
            })}
            error={errors.email}
            label="Email"
          />
          <InputControl
            defaultValue={profile.fullName}
            required={true}
            register={register("fullName", {
              required: {
                value: true,
                message: "Họ tên không được bỏ trống",
              },
            })}
            error={errors.fullName}
            label="Họ tên"
          />
          <InputControl
            defaultValue={profile.phone}
            required={true}
            register={register("phone", {
              required: {
                value: true,
                message: "Số điện thoại không được bỏ trống",
              },
              pattern: {
                value: /(84|0[3|5|7|8|9])+([0-9]{8})\b/g,
                message: "Số điện thoại không hợp lệ",
              },
            })}
            error={errors.phone}
            label="Số điện thoại"
          />
          <div>
            <button type="submit" className={styles.btn}>
              Cập nhật
            </button>
          </div>
        </form>
      </>
    </AccountLayout>
  ) : null;
};

export default Profile;
