import { ProfileForm } from "@/components";
import { AccountLayout } from "@/layouts";
import { requireLoginProps } from "@/lib";
import { UserModel } from "@/models";
import { UserJson } from "@/types/json";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";

type Props = {
  profile: UserJson | null;
};

const Profile = ({ profile }: Props) => {
  return (
    <AccountLayout
      titleHeading="Thông tin tài khoản"
      profile={new UserModel(profile)}
    >
      <>
        <Head>
          <title>Thông tin tài khoản</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProfileForm />
      </>
    </AccountLayout>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return requireLoginProps(context);
};

export default Profile;
