import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { ButtonControl, DataManagement, DataTable } from "@/components";
import { AdminLayout } from "@/layouts";
import { confirmDialogActions } from "@/redux/slice/confirmDialogSlice";
import { orderActions, orderSelector } from "@/redux/slice/orderSlice";
import { useAppDispatch } from "@/redux/store";
import helper from "@/utils/helpers";
import { protectedRoutes } from "@/utils/routes";
import { UserJson } from "@/types/json";
import { UserModel, OrderModel } from "@/models";
import { requireAdminProps } from "@/lib";
import { GetServerSidePropsContext } from "next";

type Props = { profile: UserJson | null };
const LIMIT = 10;
const Orders = ({ profile }: Props) => {
  const appDispatch = useAppDispatch();
  const router = useRouter();
  const { orderData } = useSelector(orderSelector);

  useEffect(() => {
    const { p, sortBy, sortType } = router.query;
    appDispatch(
      orderActions.fetchGetAll({
        p: +`${p}` || 1,
        limit: LIMIT,
        sortBy: `${sortBy || "id"}`,
        sortType: `${sortType}` === "ASC" ? "ASC" : "DESC",
      })
    );
  }, [router.query]);

  return (
    <AdminLayout pageTitle="Đơn hàng" profile={new UserModel(profile)}>
      <>
        <Head>
          <title>Quản lý đơn hàng</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <DataManagement
          paperTitle="Danh sách đơn hàng"
          count={orderData.count}
          limit={LIMIT}
          hideCreateBtn={true}
        >
          <DataTable
            hasCheck={true}
            columns={[
              {
                style: { textAlign: "center" },
                key: "code",
                display: "Mã đơn hàng",
              },
              {
                style: { textAlign: "center" },
                key: "fullName",
                display: "Họ tên",
              },
              {
                style: { width: 100, textAlign: "center" },
                key: "phone",
                display: "Số điện thoại",
              },
              {
                style: { textAlign: "center" },
                key: "address",
                display: "Địa chỉ",
                render: (row: OrderModel) => row.getFullAddress(),
              },
              {
                style: { width: 100, textAlign: "center" },
                key: "createdAt",
                display: "Ngày tạo",
                render: (row: OrderModel) =>
                  helper.formatDateTime(row.createdAt),
              },
              {
                style: { width: 120, textAlign: "center" },
                key: "status",
                display: "Trạng thái",
                render: (row: OrderModel) => (
                  <span
                    style={{
                      background: row.isPaid
                        ? "var(--green)"
                        : row.allowCannceled
                        ? "var(--blue)"
                        : "var(--purple)",
                      padding: "3px 6px",
                      borderRadius: "5px",
                      color: "#fff",
                      fontSize: "12px",
                    }}
                  >
                    {row.status}
                  </span>
                ),
              },
              {
                style: { width: 100 },
                key: "actions",
                render: (row: OrderModel) => (
                  <>
                    <div style={{ display: "flex", alignItems: "center" }}>
                      <Link href={protectedRoutes.updateOrder(row.id)}>
                        <ButtonControl color="secondary" size="small">
                          Sửa
                        </ButtonControl>
                      </Link>
                      <ButtonControl
                        color="error"
                        onClick={() =>
                          appDispatch(
                            confirmDialogActions.show({
                              onConfirm: () => {
                                appDispatch(
                                  orderActions.fetchSoftDeleteSingle(row.id)
                                );
                              },
                            })
                          )
                        }
                        sx={{ ml: 1 }}
                        size="small"
                      >
                        Xóa
                      </ButtonControl>
                    </div>
                  </>
                ),
              },
            ]}
            rows={orderData.items}
            sortable={[
              "code",
              "fullName",
              "phone",
              "createdAt",
              "status",
              "createdAt",
            ]}
          />
        </DataManagement>
      </>
    </AdminLayout>
  );
};
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return requireAdminProps(context);
};

export default Orders;
