import Head from "next/head";
import React from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { login, LoginDTO } from "../../../apis/auth";
import { useAuthContext } from "../../../context/AuthContext";
import { DefaultLayout } from "../../../layouts";
import { MSG_SUCCESS } from "../../../utils/constants";
import styles from "../../../styles/AdminAuth.module.css";
import { useRouter } from "next/router";
import { InputControl } from "../../../components";
type Props = {};

const Login = (props: Props) => {
  const { login: _login } = useAuthContext();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginDTO>();
  const router = useRouter();
  const onSubmit: SubmitHandler<LoginDTO> = async (data) => {
    try {
      const { message, data: _data } = await login(data);
      if (message === MSG_SUCCESS) {
        _login(_data.user, _data.accessToken);
        router.back();
      }
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div>
      <>
        <Head>
          <title>Đăng nhập</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{" "}
        <main className={styles.wrapper}>
          <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
            <h1>Đăng nhập</h1>
            <InputControl
              label="Email"
              error={errors.email}
              register={register("email", {
                required: {
                  value: true,
                  message: "Email không được để trống",
                },
                pattern: {
                  value: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g,
                  message: "Email không hợp lệ",
                },
              })}
            />
            <InputControl
              type="password"
              label="Mật khẩu"
              error={errors.password}
              register={register("password", {
                required: {
                  value: true,
                  message: "Mật khẩu không được để trống",
                },
                minLength: {
                  value: 6,
                  message: "Mật khẩu ít nhất 6 kí tự",
                },
              })}
            />
            <button className={styles.btn} type="submit">
              Đăng nhập
            </button>
          </form>
        </main>
      </>
    </div>
  );
};

export default Login;
