import { AuthForm } from "@/components";
import { noRequireAdminLoginProps } from "@/lib";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { NextPage } from "next/types";
import { Fragment } from "react";

type Props = {};

const Page: NextPage<Props> = () => {
  return (
    <Fragment>
      <Head>
        <title>Đăng nhập</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: "100vh" }} className="flex-center">
        <AuthForm action="signin" hideLinks={true} />
      </div>
    </Fragment>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  return noRequireAdminLoginProps(context);
};

export default Page;
