import { LoginDTO } from "@/types/dtos";
import Head from "next/head";
import { useRouter } from "next/router";
import { SubmitHandler, useForm } from "react-hook-form";
import { InputControl } from "@/components";
import { authActions } from "@/redux/slice/authSlice";
import { useAppDispatch } from "@/redux/store";
import styles from "@/styles/_AdminAuth.module.scss";
type Props = {};

const Login = (props: Props) => {
  const appDispatch = useAppDispatch();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginDTO>();
  const router = useRouter();
  const onSubmit: SubmitHandler<LoginDTO> = async (data) => {
    appDispatch(authActions.fetchLogin(data));
    router.back();
  };
  return (
    <div>
      <>
        <Head>
          <title>Đăng nhập</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{" "}
        <main className={styles.wrapper}>
          <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
            <h1>Đăng nhập</h1>
            <InputControl
              label="Email"
              error={errors.email}
              register={register("email", {
                required: {
                  value: true,
                  message: "Email không được để trống",
                },
                pattern: {
                  value: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g,
                  message: "Email không hợp lệ",
                },
              })}
            />
            <InputControl
              type="password"
              label="Mật khẩu"
              error={errors.password}
              register={register("password", {
                required: {
                  value: true,
                  message: "Mật khẩu không được để trống",
                },
                minLength: {
                  value: 6,
                  message: "Mật khẩu ít nhất 6 kí tự",
                },
              })}
            />
            <button className={styles.btn} type="submit">
              Đăng nhập
            </button>
          </form>
        </main>
      </>
    </div>
  );
};

export default Login;
