import { Grid, Pagination } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { myOrders } from "../../apis/order";
import { AccountLayout } from "../../layouts";
import { authActions, authSelector } from "../../redux/slice/authSlice";
import { useAppDispatch } from "../../redux/store";
import styles from "../../styles/FollowOrder.module.css";
import { MSG_SUCCESS } from "../../utils/constants";
import { formatDateTime, getThumbnailOrderItem } from "../../utils/helpers";
import {
  Order,
  OrderItem,
  ResponseItems,
  VariantValue,
} from "../../utils/types";

const LIMIT = 10;

type Props = {};

type OrderProps = Partial<{
  order: Order;
}>;

type OrderItemProps = Partial<{
  item: OrderItem;
}>;

const Item = ({ item }: OrderItemProps) => {
  return item ? (
    <>
      <Image
        width={100}
        height={120}
        src={getThumbnailOrderItem(item)}
        alt="thumbnail"
        priority={true}
      />
      <div className={styles.product}>
        <div className={styles.name}>{item.productVariant?.product?.name}</div>
        {item.productVariant?.variantValues?.map(
          (variantValue: VariantValue) => {
            return (
              <div
                className={styles.variantValue}
                key={`${item?.productVariantId} - ${variantValue.id}`}
              >
                {variantValue.variant?.name}: {variantValue.value}
              </div>
            );
          }
        )}
        <div className={styles.quantity}>Số lượng: {item.quantity}</div>
        <div className={styles.price}>{item.price}</div>
      </div>
    </>
  ) : null;
};

const MyOrder = ({ order }: OrderProps) => {
  const total = order?.items.reduce(
    (p: number, c: OrderItem) => p + c.quantity * c.price,
    0
  );
  return order ? (
    <div className={styles.order}>
      <div className={styles.title}>
        <div className={styles.left}>
          <div>
            Đơn hàng {order.id} - {order.status}
          </div>
          <div>Ngày: {formatDateTime(order.createdAt)}</div>
          <div>Họ tên: {order.fullName}</div>
          <div>Điện thoại: {order.phone}</div>
          <div>
            Địa chỉ: {order.address}, {order.ward}, {order.district},{" "}
            {order.province}
          </div>
        </div>
        <div className={styles.right}>
          <div className={styles.row}>
            <span>Giá gốc: </span>
            <span>{total}</span>
          </div>
          <div className={styles.row}>
            <span>Giảm giá: </span>
            <span>0đ</span>
          </div>
          <div className={styles.row}>
            <span>Tổng cộng: </span>
            <span>{total}</span>
          </div>
          <div>
            <button
              className={styles.btn}
              disabled={order.status !== "Đang xử lý"}
            >
              Hủy
            </button>
          </div>
        </div>
      </div>
      <ul className={styles.items}>
        {order.items.map((item: OrderItem) => {
          return (
            <li
              className={styles.item}
              key={`${order?.id} - ${item.productVariantId}`}
            >
              <Item item={item} />
            </li>
          );
        })}
      </ul>
    </div>
  ) : null;
};

const FollowOrder = (props: Props) => {
  const router = useRouter();
  const appDispatch = useAppDispatch();
  const { orderData } = useSelector(authSelector);

  const handleChange = (p: number) => {
    const paramsObj: any = { ...router.query };
    if (p > 1) {
      paramsObj.p = p;
    } else {
      delete paramsObj.p;
    }
    const searchParams: string = new URLSearchParams(paramsObj).toString();
    router.push(`${window.location.pathname}?${searchParams}`);
  };

  useEffect(() => {
    appDispatch(
      authActions.fetchMyOrderData({
        ...router.query,
        limit: LIMIT,
        items: true,
      })
    );
  }, [router.query]);

  return (
    <AccountLayout titleHeading="Đơn hàng của tôi">
      <>
        <Head>
          <title>Đơn hàng của tôi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
      <Grid container columnSpacing={2} rowSpacing={2}>
        {orderData.items.map((order: Order) => {
          return (
            <Grid item xs={12} key={order.id}>
              <MyOrder order={order} />
            </Grid>
          );
        })}
        {orderData.count > 0 ? (
          <Grid item xs={12}>
            <Pagination
              count={Math.ceil(orderData.count / LIMIT)}
              sx={{ ul: { justifyContent: "center" } }}
              variant="outlined"
              shape="rounded"
              showLastButton
              showFirstButton
              page={router.query && router.query.p ? +router.query.p : 1}
              onChange={(e, page) => handleChange(page)}
            />
          </Grid>
        ) : null}
      </Grid>
    </AccountLayout>
  );
};

export default FollowOrder;
