import React from "react";
import Head from "next/head";
import Image from "next/image";
import { MSG_SUCCESS } from "../../utils/constants";
import { getAllBlogsPublic } from "../../apis/blog";
import { Blog } from "../../utils/types";
import { DefaultLayout } from "../../layouts";
import { Container, Box } from "@mui/material";

type Props = {
  blog: Blog;
};

const BlogBySlug = ({ blog }: Props) => {
  return (
    <DefaultLayout>
      <>
        <Head>
          <title>{blog ? blog.title : "Bài viết"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Container maxWidth="lg">
            <Box sx={{ width: "100%", position: "relative", height: "480px" }}>
              <Image
                alt=""
                priority={true}
                fill={true}
                sizes="(max-width: 768px) 100%"
                src={blog.thumbnail}
              />
            </Box>
            <div dangerouslySetInnerHTML={{ __html: blog.content }}></div>
          </Container>
        </main>
      </>
    </DefaultLayout>
  );
};

export async function getServerSideProps(context: any) {
  const { slug } = context.query;
  let blog;
  const { message: msg1, data: data1 } = await getAllBlogsPublic({
    slug,
  });
  if (msg1 === MSG_SUCCESS) {
    blog = data1.items[0];
  }

  return blog
    ? {
        props: { blog },
      }
    : {
        notFound: true,
      };
}

export default BlogBySlug;
