import { Box, Container, Grid } from "@mui/material";
import Head from "next/head";
import { BlogApi } from "../../api";
import { BlogContent, ImageFill } from "../../components";
import { DefaultLayout } from "../../layouts";
import { BlogModel } from "../../models";

type Props = {
  blog: BlogModel;
  relatedBlogs: BlogModel[];
};

const bApi = new BlogApi();
const BlogBySlug = ({ blog: _blog, relatedBlogs: _relatedBlogs }: Props) => {
  const blog = new BlogModel(_blog);
  const relatedBlogs = bApi.getListFromJson(_relatedBlogs);

  const hasRelated = relatedBlogs.length > 0;

  return (
    <DefaultLayout>
      <>
        <Head>
          <title>{blog.id > 0 ? blog.title : "Bài viết"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Container maxWidth="lg">
            <Grid container columnSpacing={2} rowSpacing={2}>
              <Grid item xs={12} lg={hasRelated ? 8 : 12}>
                <BlogContent blog={blog} />
              </Grid>
              {hasRelated ? (
                <Grid item xs={4}>
                  <Box
                    p={2}
                    sx={{
                      background: "linear-gradient(45deg, #f2f3f4, #353ef9)",
                    }}
                    mb={2}
                  >
                    Bài viết liên quan
                  </Box>

                  {relatedBlogs.map((blog, index) => {
                    return (
                      <Box
                        key={blog.id}
                        display="flex"
                        gap="12px"
                        mt={index === 0 ? 0 : 2}
                      >
                        <Box width="40%">
                          <ImageFill src={blog.thumbnail} height="66.7%" />
                        </Box>
                        <Box width="60%">
                          <h4 className="three-dot three-dot-2">
                            {blog.title}
                          </h4>
                          <span
                            className="three-dot three-dot-3"
                            style={{
                              fontSize: 14,
                              color: "gray",
                              marginTop: "4px",
                            }}
                          >
                            {blog.heading}
                          </span>
                        </Box>
                      </Box>
                    );
                  })}
                </Grid>
              ) : null}
            </Grid>
          </Container>
        </main>
      </>
    </DefaultLayout>
  );
};

export async function getServerSideProps(context: any) {
  try {
    const { slug } = context.query;
    const RELATED_BLOGS_LIMIT = 3;
    let blog: BlogModel = new BlogModel();
    let relatedBlogs: BlogModel[] = [];
    const data = await bApi.getAll({
      slug,
    });
    if (data.items.length > 0) blog = data.items[0];
    if (blog.id > 0) {
      const data2 = await bApi.getAll({
        blogCategoryId: blog.blogCategoryId,
        limit: RELATED_BLOGS_LIMIT,
      });
      if (data2.items.length > 1) {
        relatedBlogs = data2.items.filter(
          (item) => blog && item.id !== blog.id
        );
      }
    }
    return {
      props: {
        blog: JSON.parse(JSON.stringify(blog)),
        relatedBlogs: JSON.parse(JSON.stringify(relatedBlogs)),
      },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

export default BlogBySlug;
