import { OrderDiscountApi } from "@/api";
import {
  ButtonControl,
  InputControl,
  PaymentForm,
  RadioControl,
  SelectControl,
} from "@/components";
import { useDefaultLayoutContext } from "@/context/DefaultLayoutContext";
import { DefaultLayout } from "@/layouts";
import { getProfileProps } from "@/lib";
import { OrderDiscountModel, UserAddressModel, UserModel } from "@/models";
import provinces from "@/province.json";
import { authSelector } from "@/redux/slice/authSlice";
import {
  cartActions,
  cartReducer,
  cartSelector,
} from "@/redux/slice/cartSlice";
import { fetchSelector } from "@/redux/slice/fetchSlice";
import { orderActions, orderSelector } from "@/redux/slice/orderSlice";
import { snackbarActions } from "@/redux/slice/snackbarSlice";
import {
  userAddressActions,
  userAddressSelector,
} from "@/redux/slice/userAddressSlice";
import { useAppDispatch } from "@/redux/store";
import styles from "@/styles/_Payment.module.scss";
import { CheckoutDTO } from "@/types/dtos";
import { DistrictJson, ProvinceJson, UserJson, WardJson } from "@/types/json";
import { publicRoutes } from "@/utils/routes";
import { Container, Grid } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { GetServerSidePropsContext, NextPage } from "next/types";
import { ChangeEvent, useEffect, useMemo, useReducer, useRef } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { useSelector } from "react-redux";

type Props = {
  profile: UserJson | null;
};
const Page: NextPage<Props> = ({ profile }) => {
  return (
    <DefaultLayout
      profile={new UserModel(profile)}
      hideFooter={true}
      hideHeader={true}
    >
      <>
        <Head>
          <title>Thanh toán đơn hàng</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
      <Container maxWidth="lg" sx={{ marginBlock: "24px" }}>
        <PaymentForm />
      </Container>
    </DefaultLayout>
  );
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { props } = await getProfileProps(context);

  return { props };
};

export default Page;
